In [2]:
import numpy as np
grid_size=4
discount_factor=0.8
reward_obstacle=-1
reward_goal=10
reward_step=-0.1
grid=np.zeros((grid_size,grid_size))
obstacles=[(1,1),(2,2),(3,0)]
for obstacle in obstacles:
  grid[obstacle]=1
reward_grid=np.full((grid_size,grid_size),reward_step)
for obstacle in obstacles:
  reward_grid[obstacle]=reward_obstacle
actions=[(0,1),(0,-1),(1,0),(-1,0)]
value_function=np.zeros((grid_size,grid_size))
def is_valid_state(x,y):
  return 0<=x<grid_size and 0<=y<grid_size and grid[x][y]==0
def bellman_update():
  new_value_function=np.copy(value_function)
  for i in range(grid_size):
    for j in range(grid_size):
      if (i,j) in obstacles:
        continue
      value_sum=0
      for action in actions:
        new_x,new_y=i+action[0],j+action[1]
        if is_valid_state(new_x,new_y):
          value_sum+=0.25*(reward_grid[new_x][new_y]+discount_factor*value_function[new_x][new_y])
      new_value_function[i,j]=reward_grid[i,j]+discount_factor*value_sum
  return new_value_function
iterations=100
for iteration in range(iterations):
  value_function=bellman_update()
print("Optimal Value Function after iteration:")
print(value_function)

Optimal Value Function after iteration:
[[-0.20752299 -0.21586654 -0.26664288 -0.22532572]
 [-0.20615213  0.         -0.22532572 -0.26664288]
 [-0.20592785 -0.20589691  0.         -0.21586654]
 [ 0.         -0.20592785 -0.20615213 -0.20752299]]
